version: "3"
services:
  server:
    image: kub-noob
    container_name: kub-noob
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - ./node_modules:/app/node_modules
      - ./:/app
    command: dev
